apps/accounts/urls.py
from django.urls import path

from .views import (
    CounterPartyAccountListView,
    DocumentsListView, DocumentCreateView,
    DocumentApproveView, DocumentCancelView,
)

urlpatterns = [
    path('documents', DocumentsListView.as_view()),
    path('documents/<slug:pk>/approve', DocumentApproveView.as_view()),
    path('documents/<slug:pk>/cancel', DocumentCancelView.as_view()),
    path('create_document/', DocumentCreateView.as_view()),
    path('account63/', CounterPartyAccountListView.as_view()),
]

furniture/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Furniture API",
      default_version='',
      description="Furniture API",
   ),
   public=True,
   permission_classes=(permissions.IsAuthenticated,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('apps.project.urls')),
    path('api/', include('apps.constructor.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('', include('apps.accounts.urls')),
    path('', include('apps.ui.urls')),
    path('project/<int:id>', include('apps.ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/accounts/models.py
from datetime import timedelta
from decimal import Decimal

from django.db import models
from django.db.transaction import atomic
from django.utils import timezone


class CounterParty(models.Model):
    class Meta:
        verbose_name = 'Контрагент'

    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        is_new_obj = False
        if not self.pk:
            is_new_obj = True
        super(CounterParty, self).save(**kwargs)
        if is_new_obj:
            Account.objects.create(counter_party=self, type=AccountType.CounterPartyDesk.value)


class Product(models.Model):
    class Meta:
        verbose_name = 'Товар'

    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class AccountType(models.IntegerChoices):
    MainDesk = 301, 'Каса'
    CounterPartyDesk = 631, 'Рахунок контрагента'


class Account(models.Model):
    class Meta:
        verbose_name = 'Каса'

    type = models.IntegerField(choices=AccountType.choices)
    counter_party = models.ForeignKey(CounterParty, on_delete=models.SET_NULL, null=True, blank=True)
    start_debit = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0.0'))

    def __str__(self):
        if self.counter_party:
            return f'{self.type} {self.counter_party}'
        return f'{self.type}'


class DocumentType(models.IntegerChoices):
    IncomingCashOrderFromCounterParty = 1, 'Прихідний касовий ордер від контрагента'
    IncomingCashOrderFromAccountablePerson = 2, 'Повернення готівки від підзвітної особи'
    OutcomeCashOrderToCounterParty = 3, 'Оплата контрагенту'
    OutcomeCashOrderToAccountablePerson = 4, 'Видача готівки підзвітній особі'
    OutcomeCashOrderToCustomer = 5, 'Поверення готівки покупцеві'


class DocumentStatus(models.TextChoices):
    Created = 'created', 'Не проведено'
    Accounted = 'accounted', 'Проведено'
    Canceled = 'canceled', 'Скасовано'


class Document(models.Model):
    type = models.IntegerField(choices=DocumentType.choices)
    amount = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    credit_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='credit_documents')
    debit_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='debit_documents')
    number = models.CharField(max_length=200)
    status = models.CharField(max_length=50, choices=DocumentStatus.choices)
    note = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    @atomic()
    def save(self, **kwargs):
        if not self.number:
            today = timezone.now()
            cnt = Document.objects.filter(type=self.type, created__gte=today - timedelta(days=1)).count()
            self.number = f'{today.strftime("%d%m")}/{cnt + 1}'
        if not self.status:
            self.status = DocumentStatus.Created.value

        super(Document, self).save(**kwargs)

        Transfer.objects.create(
            account=self.debit_account,
            from_account=self.credit_account,
            debit=self.amount, note=self.note, document=self
        )
        Transfer.objects.create(
            account=self.credit_account,
            from_account=self.debit_account,
            credit=self.amount, note=self.note, document=self
        )
        self.status = DocumentStatus.Accounted.value

    @atomic()
    def cancel(self):
        Transfer.objects.filter(document=self).delete()
        self.status = DocumentStatus.Canceled.value
        self.save()


class Transfer(models.Model):
    class Meta:
        verbose_name = 'Рух коштів'

    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='operations')
    from_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='+')
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    debit = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    credit = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    created = models.DateTimeField(auto_now_add=True)
    note = models.TextField(blank=True)

apps/accounts/forms.py
from django import forms

from apps.accounts.models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        exclude = ('number', 'status')


class DatesForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

apps/accounts/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, DetailView, ListView

from .forms import DocumentForm, DatesForm
from .models import AccountType, Transfer, Document, Account


class DocumentCreateView(FormView):
    form_class = DocumentForm
    success_url = '/documents'
    template_name = 'accounts/create_document.html'

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.INFO, "Документ додано")
        return super(DocumentCreateView, self).form_valid(form)


class DocumentsListView(ListView):
    queryset = Document.objects.all()
    template_name = 'accounts/documents.html'
    context_object_name = 'documents'


@method_decorator(csrf_exempt, name='dispatch')
class DocumentApproveView(DetailView):
    queryset = Document.objects.all()

    def post(self, request, *args, **kwargs):
        document = self.get_object()
        document.apply()
        return HttpResponse(status=200)


@method_decorator(csrf_exempt, name='dispatch')
class DocumentCancelView(DetailView):
    queryset = Document.objects.all()

    def post(self, request, *args, **kwargs):
        document = self.get_object()
        document.apply()
        return HttpResponse(status=200)


class CounterPartyAccountListView(ListView):
    queryset = Transfer.objects.filter(account__type=AccountType.CounterPartyDesk)
    template_name = 'accounts/account.html'
    context_object_name = 'transfers'

    def get_queryset(self):
        queryset = super(CounterPartyAccountListView, self).get_queryset()
        form = DatesForm(self.request.GET)
        if not form.is_valid():
            return queryset
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')
        if start_date:
            queryset = queryset.filter(created__gte=start_date)
        if end_date:
            queryset = queryset.filter(created__lte=end_date)
        return queryset

templates/accounts/account.html
{% extends 'accounts/base.html' %}

{% block content %}

    <h2>Картка рахунку 63</h2>

    <div class="row">
        <label for="start">Початкова дата:</label>
        <input type="date" id="start_date">
        <label for="start">Кінцева дата:</label>
        <input type="date" id="end_date">
    </div>

    <button class="btn btn-primary" onclick="refresh()">Відфільтрувати</button>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Дата</th>
                <th>Дебет</th>
                <th>Кредит</th>
                <th>Контрагент</th>
            </tr>
        </thead>
        {% for transfer in transfers %}
        <tr>
            <td>{{ transfer.created | date }}</td>
            <td>{{ transfer.debit|default:'' }}</td>
            <td>{{ transfer.credit|default:'' }}</td>
            <td>{{ transfer.account.counter_party.name }}</td>
        </tr>
        {% endfor %}
    </table>

    <script>
        function refresh() {
            const startDate = document.getElementById('start_date')
            const endDate = document.getElementById('end_date')

            window.location.replace(`/account63?start_date=${startDate.value}&end_date=${endDate.value}`);
        }

        (function (){
            const urlParams = new URLSearchParams(window.location.search);
            const startDate = urlParams.get('start_date');
            const endDate = urlParams.get('end_date');

            document.getElementById("start_date").value = startDate;
            document.getElementById("end_date").value = endDate;
        })()
    </script>
{% endblock %}

templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Каса</title>
</head>
<body>
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

templates/accounts/create_document.html
{% extends 'accounts/base.html' %}

{% load bootstrap5 %}

{% block content %}

    <h1>Створення документу</h1>

    <form action="." method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

templates/accounts/documents.html
{% extends 'accounts/base.html' %}

{% block content %}
    <h2>Журнал операцій</h2>

    <a class="button btn btn-secondary" href="/create_document">Додати документ</a>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Дата</th>
                <th>Назва документу</th>
                <th>Номер документу</th>
                <th>Рахунок дебету</th>
                <th>Рахунок кредиту</th>
                <th>Сума</th>
                <th>Зміст</th>
                <th>Статус</th>
            </tr>
        </thead>
        {% for document in documents %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ document.created | date }}</td>
            <td>{{ document.get_type_display }}</td>
            <td>{{ document.number }}</td>
            <td>{{ document.debit_account }}</td>
            <td>{{ document.credit_account }}</td>
            <td>{{ document.amount }}</td>
            <td>{{ document.note }}</td>
            <td>
                {{ document.get_status_display }}
                {% if document.status == 'accounted' %}
                    <button class="btn btn-secondary" onclick="cancelDocument({{ document.id }})">Скасувати проведення</button>
                {% else %}
                    <button class="btn btn-primary" onclick="approveDocument({{ document.id }})">Провести</button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>


    <script>
        async function approveDocument(docId) {
            await fetch(`/documents/${docId}/approve`, { method: 'POST' })
            location.reload()
        }

        async function cancelDocument(docId) {
            await fetch(`/documents/${docId}/cancel`, { method: 'POST' })
            location.reload()
        }
    </script>

{% endblock %}